# SPDX-License-Identifier: Apache-2.0 OR MIND-UCAL-1.0
# © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
[workspace]
members = [
    "crates/rmg-core",
    "crates/rmg-ffi",
    "crates/rmg-wasm",
    "crates/rmg-cli",
    "crates/rmg-geom",
    "crates/rmg-benches"
]
resolver = "2"

[workspace.dependencies]
rmg-core = { version = "0.1.0", path = "crates/rmg-core" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.bench]
# Derive from release but optimize for throughput and faster builds
opt-level = 3
lto = false
codegen-units = 16
debug = true
panic = "abort"
strip = false
